MetaDataFormat = "toml"
theme = "lanyon-hugo"
languageCode = "en-us"

baseurl = "https://www-users.cs.umn.edu/~harper/"
canonifyurls = true

[author]
    name = "Max"

[permalinks]
    post = "/blog/:title/"
    fixed = ":title/"

[taxonomies]
    category = "categories"

[params]
    # lanyon config
    Title = "Max Harper"
    Tagline = "GroupLens Research Scientist"
    Author = "Max"
    DateForm = "Jan 2 2006"
    [params.Github]
        Url = "http://github.com/tummychow/lanyon-hugo"
